version: '1'

networks:
  marine:
    external: true

services:
  autentication-backend:
    container_name: auth-backend
    image: marine-auth-backend:0.1.0
    build: .
    restart: always
    environment:
      PORT: $PORT
      DATABASE_URL: $DATABASE_URL
      SECRET_SEED: $SECRET_SEED
      PRISMA_BINARY: $PRISMA_BINARY
    networks:
      - marine
    
